### ISSUE TITLE
Refresh Accounts

### ISSUE THREAD

**Issue by linkRace** [dhleong/pepper-mint#12]
Other APIs such as https://github.com/mrooney/mintapi have a way to initiate an account refresh to ensure transaction and financial data is up-to-date.  Is there a way to do this here that I'm missing?

Currently, the only way I can seemingly get the data to refresh is to log in to Mint in the browser to trigger it.

**Comment by dhleong** [comment]
I may not have documented it in the README, but there is! Browse the source for `refreshAndWaitIfNeeded()`. It's not 100% perfect—it seems there may be some waiting that may need to be done after `refreshAndWaitIfNeeded()` completes before updated budget data, at least, is available—but it does initiate the refresh. Or perhaps it's just a result of my using the `doneRefreshing()` callback to finish early, and Mint doesn't actually update anything until *all* accounts are done refreshing (which seems insane, but... who knows). 

Give it a shot and let me know how it works for you! If you see any ways to improve it, please send a PR! :)
