### ISSUE TITLE
Headless

### ISSUE THREAD

**Issue by maltepet** [dhleong/pepper-mint#17]
Is there a way to get this to run in headless selenium?

I tried both of these methods, but the console window just hangs out
```.setChromeOptions(new chrome.Options().headless())```
and
```.setChromeOptions(new chrome.Options().addArguments('--headless'))```

**Comment by dhleong** [comment]
It might be, but frequently you have to enter in a 2FA code into the browser that Mint sends to your email or phone number, so it wouldn't be worthwhile. That's probably why the console just hangs for you.
