### ISSUE TITLE
slight error on the NPM page had me confused for a bit

### ISSUE THREAD

**Issue by ultralame** [dhleong/pepper-mint#4]
Just to save people some confusion you might consider updating the NPM page example from `return mint.accounts();` to the correct `return mint.getAccounts();` that you have on github. I'm a relative noob so it took me a while to figure out the problem.

Anyway, thanks for the excellent module! You've saved me loads of work. [^_^]

**Comment by dhleong** [comment]
Oh right, NPM! I merged a pull request fixing this a bit ago but forgot I had to publish to NPM. 

Sorry for the confusion, and thanks for the heads up :) I'll publish to NPM when I get back to a computer.
